#!/usr/bin/env python3
"""Generate Mermaid `graph TD` of the semantic layer.

Output: portal/erd-semantic-layer.mmd

Reads:
  semantics/views/*.view.yml   — each view has `name`, `table`, `measures[]`
  semantics/topics/*.topic.yml — each topic has `name`, `views[]`

Renders three layers:
  Topics  →  Views  →  Base tables (gold/bronze)

The page generator (generate_erd_page.py) embeds this in HTML.
"""
from __future__ import annotations

import glob
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
VIEWS_DIR = REPO_ROOT / "semantics" / "views"
TOPICS_DIR = REPO_ROOT / "semantics" / "topics"
OUT_PATH = REPO_ROOT / "portal" / "erd-semantic-layer.mmd"


def sanitize(s: str) -> str:
    return s.replace("-", "_").replace(".", "_").replace(" ", "_")


def main() -> int:
    views: dict[str, dict] = {}
    topics: dict[str, list[str]] = {}
    base_tables: set[str] = set()

    for vf in sorted(glob.glob(str(VIEWS_DIR / "*.view.yml"))):
        with open(vf) as f:
            doc = yaml.safe_load(f) or {}
        view_name = doc.get("name") or Path(vf).stem.replace(".view", "")
        base = doc.get("table")
        measures = [m.get("name") for m in (doc.get("measures") or []) if m.get("name")]
        views[view_name] = {"base_table": base, "measures": measures}
        if base:
            base_tables.add(base)

    for tf in sorted(glob.glob(str(TOPICS_DIR / "*.topic.yml"))):
        with open(tf) as f:
            doc = yaml.safe_load(f) or {}
        topic_name = doc.get("name") or Path(tf).stem.replace(".topic", "")
        topics[topic_name] = list(doc.get("views") or [])

    lines = [
        "graph TD",
        "    %% Auto-generated by scripts/generate_semantic_layer_diagram.py",
        "",
        "    classDef topicNode fill:#dceefc,stroke:#3a8fc1,color:#0b3a5c",
        "    classDef viewNode fill:#fcf3d9,stroke:#c19d3a,color:#5c4a0b",
        "    classDef tableNode fill:#e1f5e6,stroke:#3aa86a,color:#0c4920",
        "",
    ]

    if topics:
        lines.append('    subgraph topics_group["Topics"]')
        for topic in topics:
            tid = sanitize(topic)
            lines.append(f'        T_{tid}["{topic}"]:::topicNode')
        lines.append("    end")

    if views:
        lines.append('    subgraph views_group["Views (.view.yml)"]')
        for view_name, info in views.items():
            vid = sanitize(view_name)
            label = view_name
            if info["measures"]:
                label = f'{view_name}<br/><small>{len(info["measures"])} measure{"s" if len(info["measures"]) != 1 else ""}</small>'
            lines.append(f'        V_{vid}["{label}"]:::viewNode')
        lines.append("    end")

    if base_tables:
        lines.append('    subgraph tables_group["Base tables (warehouse)"]')
        for tbl in sorted(base_tables):
            tid = sanitize(tbl)
            lines.append(f'        BT_{tid}(["{tbl}"]):::tableNode')
        lines.append("    end")

    for topic, members in topics.items():
        tid = sanitize(topic)
        for member in members:
            mid = sanitize(member)
            lines.append(f"    T_{tid} --> V_{mid}")

    for view_name, info in views.items():
        if info["base_table"]:
            vid = sanitize(view_name)
            bid = sanitize(info["base_table"])
            lines.append(f"    V_{vid} --> BT_{bid}")

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {OUT_PATH} ({len(topics)} topics, {len(views)} views, {len(base_tables)} base tables)")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
