#!/usr/bin/env python3
"""Generate Mermaid `flowchart` source for the warehouse layout.

Output: portal/erd-warehouse.mmd

Tier-grouped overview: Bronze / Silver (placeholder until MVP 3) /
Gold / Admin subgraphs with tier coloring. FK relationships rendered
as arrows between tables; a subgraph-level "dbt" arrow shows the
bronze → gold flow conceptually without exploding into full lineage.

Switched from `erDiagram` to `flowchart LR` in Session 51 because the
erDiagram format had no tier grouping or coloring support in Mermaid
10.x. Column-level details live on /profile and /docs/ — the warehouse
page now answers "what tier is each table in and how do they connect"
rather than "what columns does each table have."

The page generator (generate_erd_page.py) embeds this in the HTML.
Reads bronze + gold + admin schema files; relationships are discovered
from `relationships` tests on column data_tests.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

TIER_SCHEMA_FILES = {
    "bronze": REPO_ROOT / "dbt" / "models" / "bronze" / "schema.yml",
    "silver": REPO_ROOT / "dbt" / "models" / "silver" / "schema.yml",
    "gold":   REPO_ROOT / "dbt" / "models" / "gold"   / "schema.yml",
    "admin":  REPO_ROOT / "dbt" / "models" / "admin"  / "schema.yml",
}
OUT_PATH = REPO_ROOT / "portal" / "erd-warehouse.mmd"


def parse_relationship(test: dict) -> tuple[str, str] | None:
    """Return (target_model, target_field) from a relationships test dict."""
    if not isinstance(test, dict) or "relationships" not in test:
        return None
    args = test["relationships"]
    if "arguments" in args:
        args = args["arguments"]
    to = args.get("to", "")
    m = re.search(r"ref\(['\"]([^'\"]+)['\"]\)", to)
    if not m:
        return None
    return m.group(1), args.get("field", "")


def main() -> int:
    # tier -> list of model names; relationships = (src_model, src_col, tgt_model)
    tier_models: dict[str, list[str]] = {tier: [] for tier in TIER_SCHEMA_FILES}
    relationships: list[tuple[str, str, str]] = []

    for tier, sf in TIER_SCHEMA_FILES.items():
        if not sf.exists():
            continue
        with open(sf) as f:
            doc = yaml.safe_load(f)
        for model in doc.get("models", []):
            name = model["name"]
            tier_models[tier].append(name)
            for col in model.get("columns", []):
                col_name = col["name"]
                if col_name.startswith("_"):
                    continue
                for test in col.get("data_tests", []) or col.get("tests", []) or []:
                    rel = parse_relationship(test)
                    if rel:
                        target, _target_field = rel
                        relationships.append((name, col_name, target))

    lines = [
        "flowchart LR",
        "    %% Auto-generated by scripts/generate_warehouse_erd.py",
        "    %% Tier-grouped overview. Column details live on /profile + /docs/.",
        "",
        "    classDef bronzeNode fill:#efe0c8,stroke:#a07028,color:#3d2806",
        "    classDef silverNode fill:#e8e8e8,stroke:#888888,color:#333333,stroke-dasharray:4 3",
        "    classDef goldNode   fill:#fff4c8,stroke:#c19d3a,color:#5c4a0b",
        "    classDef adminNode  fill:#dceefc,stroke:#3a8fc1,color:#0b3a5c",
        "",
    ]

    tier_label = {
        "bronze": "Bronze — source mirrors",
        "silver": "Silver — curated (MVP 3, coming soon)",
        "gold":   "Gold — analyst-facing",
        "admin":  "Admin — pipeline observability",
    }
    tier_class = {
        "bronze": "bronzeNode",
        "silver": "silverNode",
        "gold":   "goldNode",
        "admin":  "adminNode",
    }

    # Each subgraph holds the tier's models, or a placeholder if empty.
    for tier in ("bronze", "silver", "gold", "admin"):
        models = sorted(tier_models[tier])
        lines.append(f'    subgraph {tier}_group["{tier_label[tier]}"]')
        if models:
            for m in models:
                node_id = f"{tier[0]}__{m}"
                lines.append(f'        {node_id}["{m}"]:::{tier_class[tier]}')
        else:
            # Placeholder so the tier is visible even when empty (silver).
            placeholder_id = f"{tier[0]}__placeholder"
            lines.append(f'        {placeholder_id}["(none yet)"]:::{tier_class[tier]}')
        lines.append("    end")
        lines.append("")

    # Subgraph-level flow arrow: bronze --dbt--> gold (the medallion direction).
    # Silver placeholder isn't wired in until MVP 3 lands its first silver model.
    lines.append("    %% Medallion flow (conceptual — not full lineage)")
    lines.append("    bronze_group -. dbt .-> gold_group")
    lines.append("    gold_group   -. dbt .-> admin_group")
    lines.append("")

    # FK relationships between tables, deduped.
    seen: set[tuple[str, str]] = set()
    if relationships:
        lines.append("    %% Foreign-key relationships (from dbt relationships tests)")
        # Build a model -> tier index for arrow target resolution.
        model_to_tier = {m: t for t, ms in tier_models.items() for m in ms}
        for src, src_col, tgt in relationships:
            src_tier = model_to_tier.get(src)
            tgt_tier = model_to_tier.get(tgt)
            if not src_tier or not tgt_tier:
                continue
            src_id = f"{src_tier[0]}__{src}"
            tgt_id = f"{tgt_tier[0]}__{tgt}"
            edge = (src_id, tgt_id)
            if edge in seen:
                continue
            seen.add(edge)
            lines.append(f'    {src_id} -->|{src_col}| {tgt_id}')

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines) + "\n", encoding="utf-8")

    total_models = sum(len(ms) for ms in tier_models.values())
    print(f"  wrote {OUT_PATH} ({total_models} models across "
          f"{sum(1 for ms in tier_models.values() if ms)} tiers, "
          f"{len(seen)} relationships)")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
