#!/usr/bin/env python3
"""Generate per-tier Mermaid `erDiagram` blocks for /erd column-level detail.

Output: portal/erd-tier-bronze.mmd, portal/erd-tier-gold.mmd,
        portal/erd-tier-admin.mmd (silver omitted — empty tier handled
        inline as an HTML placeholder by generate_erd_page.py).

Companion to generate_warehouse_erd.py (tier flowchart). This script
brings column-level detail back to /erd as four standalone erDiagrams,
one per medallion tier, sitting below the flowchart. Splitting the
detail four ways keeps each diagram within Mermaid 10.x's clean-
render range (7-12 entities each) while preserving columns + within-
tier FK relationships.

Pre-flight 2026-05-16 (Plan 25): zero cross-tier FKs in the
warehouse — every `relationships:` test in bronze/gold/admin
schema.yml resolves to a gold-tier dim. The per-tier split therefore
loses no relationship information.

Design choices:
- **Audit columns omitted.** Underscore-prefixed pipeline-metadata
  columns (`_extracted_at`, `_dlt_id`, etc.) appear on every bronze
  table and several others. Including them adds noise without
  analyst value. They remain in /docs/ and on /profile, and the
  `audit-columns-non-analytics` limitation entry flags the choice.
- **Generic type token `text`** for every column. schema.yml carries
  descriptions + tests but not data types; the source DDL in
  docs/schema.sql has the real types. Mermaid requires *some* type
  string per column line — `text` is the honest placeholder.
- **No silver .mmd emitted.** An `erDiagram` with zero entities may
  not render; the page generator substitutes an HTML placeholder.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent

TIER_SCHEMA_FILES = {
    "bronze": REPO_ROOT / "dbt" / "models" / "bronze" / "schema.yml",
    "silver": REPO_ROOT / "dbt" / "models" / "silver" / "schema.yml",
    "gold":   REPO_ROOT / "dbt" / "models" / "gold"   / "schema.yml",
    "admin":  REPO_ROOT / "dbt" / "models" / "admin"  / "schema.yml",
}
OUT_DIR = REPO_ROOT / "portal"


def parse_relationship(test: dict) -> str | None:
    """Return target model name from a relationships test dict, or None."""
    if not isinstance(test, dict) or "relationships" not in test:
        return None
    args = test["relationships"]
    if "arguments" in args:
        args = args["arguments"]
    to = args.get("to", "")
    m = re.search(r"ref\(['\"]([^'\"]+)['\"]\)", to)
    return m.group(1) if m else None


def collect_tier(schema_file: Path) -> tuple[dict[str, list[str]], list[tuple[str, str, str]]]:
    """Return (models -> [cols], [(src_table, src_col, tgt_table)])."""
    models: dict[str, list[str]] = {}
    relationships: list[tuple[str, str, str]] = []
    if not schema_file.exists():
        return models, relationships
    with open(schema_file) as f:
        doc = yaml.safe_load(f) or {}
    for model in doc.get("models", []):
        name = model["name"]
        cols: list[str] = []
        seen_col: set[str] = set()
        for col in model.get("columns", []):
            col_name = col["name"]
            if col_name.startswith("_"):
                continue
            # schema.yml's docs convention sometimes lists a column twice
            # (once for description, once with a relationships test).
            # De-dupe the *column body* output so entities don't repeat
            # the same line, but ALWAYS scan for relationships — the FK
            # tests typically live on the second entry.
            if col_name not in seen_col:
                seen_col.add(col_name)
                cols.append(col_name)
            for test in col.get("data_tests", []) or col.get("tests", []) or []:
                tgt = parse_relationship(test)
                if tgt:
                    relationships.append((name, col_name, tgt))
        models[name] = cols
    return models, relationships


def render_er_diagram(tier: str, models: dict[str, list[str]],
                      relationships: list[tuple[str, str, str]]) -> str:
    """Return Mermaid erDiagram source for a single tier."""
    lines = [
        "erDiagram",
        f"    %% Auto-generated by scripts/generate_per_tier_erd.py ({tier} tier)",
        "    %% Columns from dbt schema.yml; audit (_*) columns omitted.",
        "    %% Type token `text` is a generic placeholder — see docs/schema.sql",
        "    %% for source DDL types.",
        "",
    ]
    for name, cols in models.items():
        lines.append(f"    {name} {{")
        for col in cols:
            lines.append(f"        text {col}")
        lines.append("    }")
        lines.append("")

    # Within-tier FK arrows only. The pre-flight already established that
    # ALL relationships in the warehouse are within-gold-tier; this loop
    # tolerates cross-tier edges defensively by filtering them out.
    within_tier_targets = set(models.keys())
    seen: set[tuple[str, str]] = set()
    for src, src_col, tgt in relationships:
        if src not in within_tier_targets or tgt not in within_tier_targets:
            continue
        edge = (src, tgt, src_col)
        key = (src, tgt)
        if key in seen:
            continue
        seen.add(key)
        lines.append(f'    {src} }}o--|| {tgt} : "{src_col}"')

    return "\n".join(lines) + "\n"


def main() -> int:
    summary: list[tuple[str, int, int, bool]] = []  # tier, models, rels, wrote
    for tier, sf in TIER_SCHEMA_FILES.items():
        models, relationships = collect_tier(sf)
        if not models:
            summary.append((tier, 0, 0, False))
            # Don't emit an .mmd for an empty tier — Mermaid won't render
            # an `erDiagram` with zero entities cleanly. The page
            # generator inserts an HTML placeholder for empty tiers.
            continue
        mmd = render_er_diagram(tier, models, relationships)
        out = OUT_DIR / f"erd-tier-{tier}.mmd"
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(mmd, encoding="utf-8")
        within_tier_rels = sum(
            1 for s, _c, t in relationships
            if s in models and t in models
        )
        summary.append((tier, len(models), within_tier_rels, True))

    print("  wrote per-tier erDiagrams:")
    for tier, nm, nr, wrote in summary:
        if wrote:
            print(f"    portal/erd-tier-{tier}.mmd ({nm} models, {nr} within-tier rels)")
        else:
            print(f"    {tier}: (empty tier — no .mmd emitted; page placeholder used)")

    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
