#!/usr/bin/env python3
"""Generate Mermaid `erDiagram` source from dbt schema.yml files.

Output: portal/erd-warehouse.mmd

The page generator (generate_erd_page.py) embeds this in the HTML.
Reads bronze + gold + admin schema files; relationships are discovered
from `relationships` tests on column data_tests.

Excludes the audit/lineage columns from the ERD body to keep diagrams
readable — the underscore-prefixed pipeline-metadata columns are
documented on /profile and in dbt /docs/ instead.
"""
from __future__ import annotations

import re
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SCHEMA_FILES = [
    REPO_ROOT / "dbt" / "models" / "bronze" / "schema.yml",
    REPO_ROOT / "dbt" / "models" / "gold"   / "schema.yml",
    REPO_ROOT / "dbt" / "models" / "admin"  / "schema.yml",
]
OUT_PATH = REPO_ROOT / "portal" / "erd-warehouse.mmd"


def parse_relationship(test: dict) -> tuple[str, str] | None:
    """Return (target_model, target_field) from a relationships test dict."""
    if not isinstance(test, dict) or "relationships" not in test:
        return None
    args = test["relationships"]
    if "arguments" in args:
        args = args["arguments"]
    to = args.get("to", "")
    m = re.search(r"ref\(['\"]([^'\"]+)['\"]\)", to)
    if not m:
        return None
    return m.group(1), args.get("field", "")


def main() -> int:
    models: dict[str, list[str]] = {}
    relationships: list[tuple[str, str, str, str]] = []

    for sf in SCHEMA_FILES:
        if not sf.exists():
            continue
        with open(sf) as f:
            doc = yaml.safe_load(f)
        for model in doc.get("models", []):
            name = model["name"]
            cols = []
            for col in model.get("columns", []):
                col_name = col["name"]
                if col_name.startswith("_"):
                    continue
                cols.append(col_name)
                for test in col.get("data_tests", []) or col.get("tests", []) or []:
                    rel = parse_relationship(test)
                    if rel:
                        target, target_field = rel
                        relationships.append((name, col_name, target, target_field))
            models[name] = cols

    lines = [
        "erDiagram",
        "    %% Auto-generated by scripts/generate_warehouse_erd.py",
        "    %% From dbt schema.yml relationships tests; audit columns omitted.",
        "",
    ]
    for name, cols in models.items():
        lines.append(f"    {name} {{")
        for col in cols:
            lines.append(f"        text {col}")
        lines.append("    }")

    for src, src_col, tgt, _tgt_col in relationships:
        lines.append(f'    {src} }}o--|| {tgt} : "{src_col}"')

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"  wrote {OUT_PATH} ({len(models)} models, {len(relationships)} relationships)")
    return 0


if __name__ == "__main__":
    import sys
    sys.exit(main())
