#!/usr/bin/env python3
"""Refresh the dynamic sections of portal/index.html.

Reads counts + date ranges from the warehouse plus the active-limitation
count from `docs/limitations/*.md` frontmatter, and patches two
marker-bounded sections in `portal/index.html`:

- BEGIN_STATS / END_STATS               (6-cell stats grid)
- BEGIN_DATASET_CARDS / END_DATASET_CARDS  (2 topic cards)

The rest of `portal/index.html` is hand-edited. The generator only
rewrites between markers, so the rest of the page is safe.

Output: `portal/index.html` (in-place).
run.sh deploys to /var/www/somerville/index.html via deploy_html.
"""
from __future__ import annotations

import re
from html import escape
from pathlib import Path

import duckdb

# Local import: scripts/_nav.py is the shared nav source.
import sys as _sys
_sys.path.insert(0, str(Path(__file__).resolve().parent))
from _nav import nav_html  # noqa: E402

REPO_ROOT = Path(__file__).resolve().parent.parent
DB_PATH = REPO_ROOT / "data" / "somerville.duckdb"
HTML_PATH = REPO_ROOT / "portal" / "index.html"
LIMITATIONS_DIR = REPO_ROOT / "docs" / "limitations"


def humanize_count(n: int) -> str:
    if n >= 1_000_000:
        return f"{n / 1_000_000:.2f}M".rstrip("0").rstrip(".")
    if n >= 1_000:
        return f"{n / 1_000:.1f}K".rstrip("0").rstrip(".")
    return f"{n:,}"


def format_date_range(min_dt, max_dt) -> str:
    if min_dt is None or max_dt is None:
        return "--"
    return f"{min_dt.strftime('%Y-%m-%d')} to {max_dt.strftime('%Y-%m-%d')}"


def fetch_stats(conn) -> dict:
    """Return everything the homepage needs in one dict."""
    s = {}

    row = conn.execute("""
        SELECT
            COUNT(*) AS rows,
            MIN(date_created_dt) AS min_dt,
            MAX(date_created_dt) AS max_dt,
            COUNT(DISTINCT request_type) AS distinct_request_types,
            COUNT(DISTINCT ward) AS distinct_wards
        FROM main_gold.fct_311_requests
    """).fetchone()
    s["311_rows"] = row[0]
    s["311_min_dt"] = row[1]
    s["311_max_dt"] = row[2]
    s["311_request_types"] = row[3]
    s["311_wards"] = row[4]

    row = conn.execute("""
        SELECT
            COUNT(*) AS rows,
            MIN(incident_dt) AS min_dt,
            MAX(incident_dt) AS max_dt,
            COUNT(DISTINCT offense_category) AS distinct_categories,
            COUNT(DISTINCT ward) AS distinct_wards
        FROM main_gold.fct_crime_incidents
    """).fetchone()
    s["crime_rows"] = row[0]
    s["crime_min_dt"] = row[1]
    s["crime_max_dt"] = row[2]
    s["crime_categories"] = row[3]
    s["crime_wards"] = row[4]

    s["ward_count"] = conn.execute(
        "SELECT COUNT(*) FROM main_gold.dim_ward"
    ).fetchone()[0]

    row = conn.execute("""
        SELECT run_completed_at, run_status
        FROM main_admin.fct_pipeline_run_raw
        WHERE run_completed_at IS NOT NULL
        ORDER BY run_completed_at DESC
        LIMIT 1
    """).fetchone()
    s["last_run_at"] = row[0] if row else None
    s["last_run_status"] = row[1] if row else None

    return s


def count_active_limitations() -> tuple[int, int, int]:
    """Returns (total active, 311-affecting active, crime-affecting active).

    311-affecting: `affects:` mentions fct_311_requests, raw_311_requests,
    or any `requests.*` field.
    Crime-affecting: `affects:` mentions fct_crime_incidents,
    raw_somerville_crime, or any `crime.*` field.
    """
    n311_patterns = (
        "fct_311_requests",
        "raw_311_requests",
        "requests.",
    )
    n_crime_patterns = (
        "fct_crime_incidents",
        "raw_somerville_crime",
        "crime.",
    )
    total = 0
    n311 = 0
    n_crime = 0
    for f in LIMITATIONS_DIR.glob("*.md"):
        if f.name.startswith("_"):
            continue
        text = f.read_text()
        if "status: active" not in text:
            continue
        total += 1
        # crude affects: section detection
        affects_block = ""
        in_affects = False
        for line in text.splitlines():
            if line.startswith("affects:"):
                in_affects = True
                continue
            if in_affects:
                if line.startswith("  - "):
                    affects_block += line + "\n"
                elif line.startswith("#"):
                    break
                elif line.startswith("---"):
                    break
                elif line.strip() == "":
                    continue
                else:
                    break
        if any(p in affects_block for p in n311_patterns):
            n311 += 1
        if any(p in affects_block for p in n_crime_patterns):
            n_crime += 1
    return total, n311, n_crime


def render_stats(s: dict, total_limitations: int) -> str:
    last_run = s["last_run_at"]
    if last_run is not None:
        last_run_str = last_run.strftime("%Y-%m-%d")
    else:
        last_run_str = "--"
    return f"""<!-- BEGIN_STATS (generated by scripts/generate_homepage_summary.py) -->
  <div class="stats">
    <div class="stat">
      <div class="stat-value">{escape(humanize_count(s["311_rows"]))}</div>
      <div class="stat-label">311 requests loaded</div>
    </div>
    <div class="stat">
      <div class="stat-value">{escape(humanize_count(s["crime_rows"]))}</div>
      <div class="stat-label">Crime incidents loaded</div>
    </div>
    <div class="stat">
      <div class="stat-value">{escape(str(s["ward_count"]))}</div>
      <div class="stat-label">Wards covered</div>
    </div>
    <div class="stat">
      <div class="stat-value">{escape(str(total_limitations))}</div>
      <div class="stat-label">Documented limitations</div>
    </div>
    <div class="stat">
      <div class="stat-value">{escape(s["311_max_dt"].strftime("%Y-%m-%d") if s["311_max_dt"] else "--")}</div>
      <div class="stat-label">Latest data point (311)</div>
    </div>
    <div class="stat">
      <div class="stat-value">{escape(last_run_str)}</div>
      <div class="stat-label">Last pipeline run</div>
    </div>
  </div>
  <!-- END_STATS -->"""


def render_dataset_cards(s: dict, n311: int, n_crime: int) -> str:
    return f"""<!-- BEGIN_DATASET_CARDS (generated by scripts/generate_homepage_summary.py) -->
    <div class="dataset-grid">
      <div class="dataset-card">
        <div class="dataset-card-eyebrow">Topic &middot; service_requests</div>
        <div class="dataset-card-title">311 service requests</div>
        <div class="dataset-card-row">
          <span class="dataset-card-key">Rows</span>
          <span class="dataset-card-val">{escape(f"{s['311_rows']:,}")}</span>
        </div>
        <div class="dataset-card-row">
          <span class="dataset-card-key">Date range</span>
          <span class="dataset-card-val">{escape(format_date_range(s["311_min_dt"], s["311_max_dt"]))}</span>
        </div>
        <div class="dataset-card-row">
          <span class="dataset-card-key">Request types</span>
          <span class="dataset-card-val">{escape(f"{s['311_request_types']:,}")}</span>
        </div>
        <div class="dataset-card-row">
          <span class="dataset-card-key">Wards covered</span>
          <span class="dataset-card-val">{escape(str(s["311_wards"]))} / {escape(str(s["ward_count"]))}</span>
        </div>
        <div class="dataset-card-limits">
          {escape(str(n311))} active limitations affecting this dataset &mdash;
          <a href="/trust">see /trust</a>
        </div>
      </div>
      <div class="dataset-card">
        <div class="dataset-card-eyebrow">Topic &middot; public_safety</div>
        <div class="dataset-card-title">Crime incidents</div>
        <div class="dataset-card-row">
          <span class="dataset-card-key">Rows</span>
          <span class="dataset-card-val">{escape(f"{s['crime_rows']:,}")}</span>
        </div>
        <div class="dataset-card-row">
          <span class="dataset-card-key">Date range</span>
          <span class="dataset-card-val">{escape(format_date_range(s["crime_min_dt"], s["crime_max_dt"]))}</span>
        </div>
        <div class="dataset-card-row">
          <span class="dataset-card-key">Offense categories</span>
          <span class="dataset-card-val">{escape(str(s["crime_categories"]))}</span>
        </div>
        <div class="dataset-card-row">
          <span class="dataset-card-key">Wards covered</span>
          <span class="dataset-card-val">{escape(str(s["crime_wards"]))} / {escape(str(s["ward_count"]))}</span>
        </div>
        <div class="dataset-card-limits">
          {escape(str(n_crime))} active limitations affecting this dataset &mdash;
          <a href="/trust">see /trust</a>
        </div>
      </div>
    </div>
    <!-- END_DATASET_CARDS -->"""


_STATS_RE = re.compile(
    r"<!-- BEGIN_STATS.*?-->.*?<!-- END_STATS -->",
    re.DOTALL,
)
_CARDS_RE = re.compile(
    r"<!-- BEGIN_DATASET_CARDS.*?-->.*?<!-- END_DATASET_CARDS -->",
    re.DOTALL,
)
_NAV_RE = re.compile(
    r"<!-- BEGIN_NAV.*?-->.*?<!-- END_NAV -->",
    re.DOTALL,
)


def main() -> None:
    if not DB_PATH.exists():
        raise SystemExit(f"DuckDB file missing: {DB_PATH}")
    if not HTML_PATH.exists():
        raise SystemExit(f"HTML file missing: {HTML_PATH}")

    conn = duckdb.connect(str(DB_PATH), read_only=True)
    try:
        stats = fetch_stats(conn)
    finally:
        conn.close()

    total_limits, n311, n_crime = count_active_limitations()

    stats_html = render_stats(stats, total_limits)
    cards_html = render_dataset_cards(stats, n311, n_crime)
    nav_block = (
        "<!-- BEGIN_NAV (rewritten by scripts/generate_homepage_summary.py "
        "from scripts/_nav.py) -->\n  "
        + nav_html(active="home")
        + "\n  <!-- END_NAV -->"
    )

    html = HTML_PATH.read_text()

    new_html, stats_subs = _STATS_RE.subn(stats_html, html)
    if stats_subs != 1:
        raise SystemExit(
            f"Expected exactly 1 BEGIN_STATS block, found {stats_subs}"
        )

    new_html, cards_subs = _CARDS_RE.subn(cards_html, new_html)
    if cards_subs != 1:
        raise SystemExit(
            f"Expected exactly 1 BEGIN_DATASET_CARDS block, found {cards_subs}"
        )

    new_html, nav_subs = _NAV_RE.subn(nav_block, new_html)
    if nav_subs != 1:
        raise SystemExit(
            f"Expected exactly 1 BEGIN_NAV block, found {nav_subs}"
        )

    HTML_PATH.write_text(new_html)
    print(f"refreshed portal/index.html:")
    print(f"  311:   {stats['311_rows']:>10,} rows, {stats['311_wards']} wards, "
          f"{stats['311_request_types']} request types")
    print(f"  crime: {stats['crime_rows']:>10,} rows, {stats['crime_wards']} wards, "
          f"{stats['crime_categories']} offense categories")
    print(f"  wards: {stats['ward_count']}")
    print(f"  limitations: {total_limits} active "
          f"({n311} affect 311, {n_crime} affect crime)")
    if stats["last_run_at"] is not None:
        print(f"  last run: {stats['last_run_at']} ({stats['last_run_status']})")


if __name__ == "__main__":
    main()
